### ISSUE TITLE
Vert.x 3 support

### ISSUE THREAD

**Issue by Jotschi** [amoAHCP/spring-vertx-mod#1]
The module is currently not compatible with Vert.x 3.

I started work on migrating the code to vertx.3

**Comment by amoAHCP** [comment]
Hi Jotschi,
Thx... it would be great .... let me know if you need some help... I'm currently working on an other vert.x3 project (https://github.com/amoAHCP/vert.x-microservice) but this was on my todo list.

**Comment by Jotschi** [comment]
Okay, DI works now but i have some questions.
I'm not sure if i get something wrong here but most of the spring verticle loaders i have seen expect in one way or another that  the user provides a spring configuration class which specifies methods for the various verticle beans. I had to add a bean definition in order to get the verticlefactory to work. (Step 2)

```
  private Verticle createSpringVerticle(final Class<?> currentVerticleClass, ClassLoader classLoader) {
        final SpringVerticle annotation = (SpringVerticle) currentVerticleClass.getAnnotation(SpringVerticle.class);
        final Class<?> springConfigClass = annotation.springConfig();
        
        // Create the parent context  
        final GenericApplicationContext genericApplicationContext = new GenericApplicationContext();
        genericApplicationContext.setClassLoader(classLoader);
        registerVertxBeans(genericApplicationContext.getBeanFactory());
        genericApplicationContext.refresh();
        genericApplicationContext.start();

        // 1. Create a new context for each verticle and use the specified spring configuration class if possible
		AnnotationConfigApplicationContext annotationConfigApplicationContext = new AnnotationConfigApplicationContext();
        annotationConfigApplicationContext.setParent(genericApplicationContext);
        annotationConfigApplicationContext.register(SpringContextConfiguration.class, springConfigClass);

        // 2. Register a bean definition for this verticle
        annotationConfigApplicationContext.registerBeanDefinition(currentVerticleClass.getSimpleName(), new VerticleBeanDefinition(currentVerticleClass));

        // 3. Add a bean factory post processor to avoid configuration issues
        annotationConfigApplicationContext.addBeanFactoryPostProcessor(new SpringSingleVerticleConfiguration(currentVerticleClass));

        // 4. Add the initialization post processor which will setup the verticle
        annotationConfigApplicationContext.getBeanFactory().addBeanPostProcessor(new SpringVerticleInitialisationPostProcessor(this.vertx));
        annotationConfigApplicationContext.refresh();
        annotationConfigApplicationContext.start();
        annotationConfigApplicationContext.registerShutdownHook();
        
        // 5. Return the verticle by fetching the bean from the context
        return (Verticle) annotationConfigApplicationContext.getBeanFactory().getBean(currentVerticleClass.getSimpleName());
    }
```

I don't yet understand why step 3. is needed. Could you perhaps elaborate Step 3?

**Comment by amoAHCP** [comment]
Hi,

the Spring verticle should look like this:

 @Component
@SpringVerticle(springConfig=TestConfiguration.class)
public class SpringVerticle extends Verticle {

The TestConfiguration is simply:
@Configuration
@ComponentScan
public class TestConfiguration

you can add here any spring configurations you want… even imports of xml… so every verticle has it’s own spring config (or you share the same config)


… so step 3… this is special ;-)

following scenario:
- you have x spring verticles in one package sharing the same/diffrent spring configurations (@SpringVerticle).
- every spring verticle creates it’s own context and without the postprocessor all the other verticles are registered in this context too… this is what I want to prevent.


Andy




> Am 16.01.2015 um 15:54 schrieb Johannes Schüth <notifications@github.com>:
> 
> Okay, DI works now but i have some questions.
> I'm not sure if i get something wrong here but most of the spring verticle loaders i have seen expect in one way or another that the user provides a spring configuration class which specifies methods for the various verticle beans. I had to add a bean definition in order to get the verticlefactory to work. (Step 2)
> 
>   private Verticle createSpringVerticle(final Class<?> currentVerticleClass, ClassLoader classLoader) {
>         final SpringVerticle annotation = (SpringVerticle) currentVerticleClass.getAnnotation(SpringVerticle.class);
>         final Class<?> springConfigClass = annotation.springConfig();
> 
>         // Create the parent context  
>         final GenericApplicationContext genericApplicationContext = new GenericApplicationContext();
>         genericApplicationContext.setClassLoader(classLoader);
>         registerVertxBeans(genericApplicationContext.getBeanFactory());
>         genericApplicationContext.refresh();
>         genericApplicationContext.start();
> 
>         // 1. Create a new context for each verticle and use the specified spring configuration class if possible
>         AnnotationConfigApplicationContext annotationConfigApplicationContext = new AnnotationConfigApplicationContext();
>         annotationConfigApplicationContext.setParent(genericApplicationContext);
>         annotationConfigApplicationContext.register(SpringContextConfiguration.class, springConfigClass);
> 
>         // 2. Register a bean definition for this verticle
>         annotationConfigApplicationContext.registerBeanDefinition(currentVerticleClass.getSimpleName(), new VerticleBeanDefinition(currentVerticleClass));
> 
>         // 3. Add a bean factory post processor to avoid configuration issues
>         annotationConfigApplicationContext.addBeanFactoryPostProcessor(new SpringSingleVerticleConfiguration(currentVerticleClass));
> 
>         // 4. Add the initialization post processor which will setup the verticle
>         annotationConfigApplicationContext.getBeanFactory().addBeanPostProcessor(new SpringVerticleInitialisationPostProcessor(this.vertx));
>         annotationConfigApplicationContext.refresh();
>         annotationConfigApplicationContext.start();
>         annotationConfigApplicationContext.registerShutdownHook();
> 
>         // 5. Return the verticle by fetching the bean from the context
>         return (Verticle) annotationConfigApplicationContext.getBeanFactory().getBean(currentVerticleClass.getSimpleName());
>     }
> I don't yet understand why step 3. is needed. Could you perhaps elaborate Step 3?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/amoAHCP/spring-vertx-mod/issues/1#issuecomment-70264168>.
> 

Andy Moncsek
amo@mailbox.org
